# Configurations
organization:
  owner: "Company Owner"

  leads:
    project_coordinator: "Project Coordinator"
    frontend_lead: "Frontend Lead"
    backend_lead: "Backend Lead"
    database_lead: "Database Lead"
    ml_lead: "ML Lead"
    devops_lead: "DevOps Lead"
    security_lead: "Security Lead"
    qa_lead: "QA Lead"
    support_lead: "Support Lead"
    solution_architect: "Solution Architect"
    uiux_lead: "UI/UX Lead"
    business_analyst: "Business Analyst"

  teams:
    business_analysts:
      count: 1
      reports_to: project_coordinator
    solution_architects:
      count: 1
      reports_to: project_coordinator
    system_designers:
      count: 1
      reports_to: solution_architect
    uiux_designers:
      count: 2
      reports_to: uiux_lead
    frontend_engineers:
      count: 2
      reports_to: frontend_lead
    backend_engineers:
      count: 2
      reports_to: backend_lead
    database_engineers:
      count: 1
      reports_to: database_lead
    ml_engineers:
      count: 1
      reports_to: ml_lead
    mlops_engineers:
      count: 1
      reports_to: ml_lead
    devops_engineers:
      count: 1
      reports_to: devops_lead
    network_security_engineers:
      count: 1
      reports_to: security_lead
    qa_engineers:
      count: 1
      reports_to: qa_lead
    support_engineers:
      count: 1
      reports_to: support_lead

# Optionally, approvals, tools, and other settings can go here as well
