agents:
  - name: business_analyst_1
    role: business_analyst
    reports_to: project_coordinator
    tools: []

  - name: solution_architect_1
    role: solution_architect
    reports_to: project_coordinator
    tools: []

  - name: system_designer_1
    role: system_designer
    reports_to: solution_architect_1
    tools: []

  - name: uiux_lead
    role: uiux_lead
    reports_to: project_coordinator
    tools: []

  - name: uiux_designer_1
    role: uiux_designer
    reports_to: uiux_lead
    tools: []

  - name: uiux_designer_2
    role: uiux_designer
    reports_to: uiux_lead
    tools: []

  - name: frontend_lead
    role: frontend_lead
    reports_to: project_coordinator
    tools: []

  - name: frontend_engineer_1
    role: frontend_engineer
    reports_to: frontend_lead
    tools: [docker_tool, github_tool]

  - name: frontend_engineer_2
    role: frontend_engineer
    reports_to: frontend_lead
    tools: [docker_tool, github_tool]

  - name: backend_lead
    role: backend_lead
    reports_to: project_coordinator
    tools: []

  - name: backend_engineer_1
    role: backend_engineer
    reports_to: backend_lead
    tools: [docker_tool, github_tool]

  - name: backend_engineer_2
    role: backend_engineer
    reports_to: backend_lead
    tools: [docker_tool, github_tool]

  - name: database_lead
    role: database_lead
    reports_to: project_coordinator
    tools: []

  - name: database_engineer_1
    role: database_engineer
    reports_to: database_lead
    tools: [docker_tool]

  - name: ml_lead
    role: ml_lead
    reports_to: project_coordinator
    tools: []

  - name: ml_engineer_1
    role: ml_engineer
    reports_to: ml_lead
    tools: [docker_tool, github_tool]

  - name: mlops_lead
    role: mlops_lead
    reports_to: ml_lead
    tools: []

  - name: mlops_engineer_1
    role: mlops_engineer
    reports_to: mlops_lead
    tools: [docker_tool]

  - name: devops_lead
    role: devops_lead
    reports_to: project_coordinator
    tools: []

  - name: devops_engineer_1
    role: devops_engineer
    reports_to: devops_lead
    tools: [docker_tool, aws_cli_tool]

  - name: security_lead
    role: security_lead
    reports_to: project_coordinator
    tools: []

  - name: network_security_engineer_1
    role: network_security_engineer
    reports_to: security_lead
    tools: []

  - name: qa_lead
    role: qa_lead
    reports_to: project_coordinator
    tools: []

  - name: qa_engineer_1
    role: qa_engineer
    reports_to: qa_lead
    tools: [docker_tool, test_runner_tool]

  - name: support_lead
    role: support_lead
    reports_to: project_coordinator
    tools: []

  - name: support_engineer_1
    role: support_engineer
    reports_to: support_lead
    tools: []

  - name: product_owner
    role: product_owner
    reports_to: project_coordinator
    tools: []

  - name: project_coordinator
    role: project_coordinator
    reports_to: product_owner
    tools: []


  - name: project_manager
    role: project_manager
    reports_to: product_owner
    tools: []


